apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-pki-to-secret-tls
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: k8s-pki-to-secret-tls
          image: bitnami/kubectl
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Create the Kubernetes Secret with the CA certificate and private key
              echo "Creating the Kubernetes Secret with the CA certificate and private key"
              export KUBECONFIG=/etc/kubernetes/admin.conf
              kubectl create secret tls kubeadm-ca \
                --cert=/etc/kubernetes/pki/ca.crt \
                --key=/etc/kubernetes/pki/ca.key \
                -n cert-manager
          volumeMounts:
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
      volumes:
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
            type: Directory
      restartPolicy: Never
  backoffLimit: 1
