apiVersion: v1
kind: Service
metadata:
  name: blockfriday
  namespace: blockfriday
spec:
  selector:
    app: blockfriday-admission-controller
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP